spring:
  liquibase:
    enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    #    url: jdbc:postgresql://localhost:5432/tehnovsky_task
    url: jdbc:postgresql://postgres:5432/tehnovsky_task

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  application:
    name: task

logging:
  file:
    name: app.log
