package com.tehnovsky.task.util.db_actions;

import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
public class DataInitializer {
    private static final String CREATE_USER_TABLE_SQL = """
            create table if not exists user_
            (
                id bigint generated by default as identity primary key,
                username varchar(100) not null
            );
                            
            """;

    private static final String CREATE_OPERATION_TABLE_SQL = """
            create table if not exists operation
            (
            id bigint generated by default as identity primary key,
            operation_type varchar(50)    not null,
            amount         numeric(10, 2) not null,
            currency       varchar(10)    not null,
            operation_date timestamp      not null,
            user_id        bigint         not null constraint fk_operation_user references user_ on delete cascade
            );
                        
            """;

    private static final String CREATE_DOCUMENT_TABLE_SQL = """
            create table if not exists document
            (
            id              bigint generated by default as identity primary key,
            document_number varchar(50)  not null unique,
            document_type   varchar(100) not null,
            user_id         bigint       not null constraint fk_document_user references user_ on delete cascade
            );
                       
            """;

    private static final String CREATE_ACCOUNT_TABLE_SQL = """
            create table if not exists account
            (
            id       bigint generated by default as identity primary key,
            balance  numeric(10, 2) not null,
            currency varchar(10)    not null,
            user_id  bigint         not null constraint fk_account_user references user_ on delete cascade
            );
                         
            """;

    public void initData(JdbcTemplate jdbcTemplate) {
        createTablesIfNotExist(jdbcTemplate);
        jdbcTemplate.execute("""
                INSERT INTO user_ (username)
                VALUES ('Bob'),
                       ('Tom'),
                       ('Kate');

                INSERT INTO account (balance, currency, user_id)
                VALUES (10.34, 'BYN', 1),
                       (0, 'USD', 1),
                       (100, 'USD', 2),
                       (0, 'BYN', 2),
                       (300, 'BYN', 3);

                INSERT INTO document (document_number, document_type, user_id)
                VALUES ('MP12345', 'PASSPORT', 1),
                       ('DL12345', 'DRIVER_LICENSE', 1),
                       ('DL54321', 'DRIVER_LICENSE', 2),
                       ('OP12345', 'PASSPORT', 3);

                INSERT INTO operation (operation_type, amount, currency, operation_date, user_id)
                VALUES ('DEPOSIT', 10.34, 'BYN', '2024-04-26 13:49:25-07', 1),
                       ('DEPOSIT', 100, 'USD', '2024-04-26 13:49:25-07', 2),
                       ('DEPOSIT', 300, 'BYN', '2024-04-26 14:49:25-07', 3);
                """);
    }

    private void createTablesIfNotExist(JdbcTemplate jdbcTemplate) {
        jdbcTemplate.execute(CREATE_USER_TABLE_SQL);
        jdbcTemplate.execute(CREATE_OPERATION_TABLE_SQL);
        jdbcTemplate.execute(CREATE_DOCUMENT_TABLE_SQL);
        jdbcTemplate.execute(CREATE_ACCOUNT_TABLE_SQL);
    }
}
